Retrieving object at: stored_a
Exception caught.
Exiting ... 
Execution completed
